### ISSUE TITLE
Add SDL_image and link to it in makefiles for all platforms, for PNG support

### ISSUE THREAD

**Issue by shirakaba** [Syreniac/verdant-octo-spork#13]
https://www.libsdl.org/projects/SDL_image/

Note: Linux doesn't seem to have an official SDL_image release corresponding to SDL2, but someone may have made one (perhaps SDL2_image-2.0.0.tar.gz on https://www.libsdl.org/projects/SDL_image/ ? or this..? https://www.archlinux.org/packages/extra/i686/sdl2_image/ ) ; we'll have to have a chat about that. All other platforms have an SDL2-compatible SDL_Image, at least.

The updates between SDL_image and SDL2_image are inconsequential to our uses, so as long as it's backwards compatible (it might not be), we could even investigate just using SDL_image for Linux.

**Comment by Syreniac** [comment]
With my commit today, I put the image loading into its own spot in the graphics.c file. This should mean that if we implement absolute path resolution, it will be going here rather than in the game.c file, which should really be kept more clean.

We also need to be careful of asprintf, it won't compile on Windows or the lab machines natively, we'll need to link it in manually if we want to use it. I think we could get away with using sprintf for now, but it's a good feature to look into later.
