### ISSUE TITLE
Ice cream cone doesn't seem to be homed in on as if it were a resource [awaiting next commit]

### ISSUE THREAD

**Issue by shirakaba** [Syreniac/verdant-octo-spork#33]

**Comment by aodl** [comment]
This is because it needs to be programmed into the bees behaviour, by the player for example. If the bee happens to fly very accurately into the center of the cone it picks it up and takes it back like resource. This actually happens sometimes accidentally anyway, but can be made far less likely by reducing the ICECREAM_PICKUP_RADIUS to a lower value than 20. It is the same situation for when it comes to actually stinging the guy :)
